### ISSUE TITLE
explorer.exe crash after running shortcut on 2nd monitor

### ISSUE THREAD

**Issue by Roan-V** [srwi/EverythingToolbar#390]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.1.0.0

### Windows Version

Windows 10 Pro 22H2 (19045.2965)

### Steps to reproduce

1. Have 2 monitors
2. Have the mouse on the non main monitor
3. Press the EverythingToolbar shortcut
4. Observe explorer.exe crashing

### Expected Behavior

explorer.exe doesn't crash

### Actual Behavior

explorer.exe crashes

### Log output

<details> <summary>EverythingToolbar.log</summary>
2023-05-25 07:28:16.1485|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.0.5.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 08:25:26.0727|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 08:25:32.1209|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.0.5.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 08:25:35.3610|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 08:29:09.3000|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.1.0.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 08:30:43.9757|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 08:30:44.2101|ERROR|EverythingToolbar.Behaviors.ThemeAwareness|Failed to get latest release version.|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EverythingToolbar.Controls.UpdateBanner.<GetLatestStableReleaseVersion>d__5.MoveNext() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\UpdateBanner.xaml.cs:line 38
2023-05-25 08:32:49.6135|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.1.0.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 10:16:10.4818|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 10:16:10.7787|ERROR|EverythingToolbar.Behaviors.ThemeAwareness|Failed to get latest release version.|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EverythingToolbar.Controls.UpdateBanner.<GetLatestStableReleaseVersion>d__5.MoveNext() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\UpdateBanner.xaml.cs:line 38
2023-05-25 11:53:55.6280|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.1.0.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 11:53:59.6764|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 11:54:00.0151|ERROR|EverythingToolbar.Behaviors.ThemeAwareness|Failed to get latest release version.|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EverythingToolbar.Controls.UpdateBanner.<GetLatestStableReleaseVersion>d__5.MoveNext() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\UpdateBanner.xaml.cs:line 38
2023-05-25 12:16:33.1537|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.1.0.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 12:16:35.6292|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 12:16:35.9860|ERROR|EverythingToolbar.Behaviors.ThemeAwareness|Failed to get latest release version.|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EverythingToolbar.Controls.UpdateBanner.<GetLatestStableReleaseVersion>d__5.MoveNext() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\UpdateBanner.xaml.cs:line 38
2023-05-25 14:32:09.7684|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.1.0.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 14:34:12.7182|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 14:34:12.9415|ERROR|EverythingToolbar.Behaviors.ThemeAwareness|Failed to get latest release version.|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EverythingToolbar.Controls.UpdateBanner.<GetLatestStableReleaseVersion>d__5.MoveNext() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\UpdateBanner.xaml.cs:line 38
2023-05-25 14:43:44.6740|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.1.0.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 14:44:05.0361|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 14:44:05.2580|ERROR|EverythingToolbar.Behaviors.ThemeAwareness|Failed to get latest release version.|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EverythingToolbar.Controls.UpdateBanner.<GetLatestStableReleaseVersion>d__5.MoveNext() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\UpdateBanner.xaml.cs:line 38
2023-05-25 14:44:12.2970|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.1.0.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 15:03:41.1887|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 15:03:46.3411|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.1.0.0 started. OS: Microsoft Windows NT 10.0.19045.0|
2023-05-25 15:03:48.7774|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-05-25 15:03:49.1368|ERROR|EverythingToolbar.Behaviors.ThemeAwareness|Failed to get latest release version.|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EverythingToolbar.Controls.UpdateBanner.<GetLatestStableReleaseVersion>d__5.MoveNext() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\UpdateBanner.xaml.cs:line 38
E
</details>

### Additional Information

I run two monitors at work, when running the EverythingToolbar shortcut with the *mouse* on the main monitor everything works fine.
When running the shortcut with the mouse on the 2nd monitor explorer.exe crashes

Of note, it doesn't matter if a program on the main monitor is selected or not, it's literally just the position of the mouse that matters

According to Event Viewer it's an error in the .NET Runtime
<details><summary>Error text:</summary>
Application: explorer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.DependencyObject.SetValue(System.Windows.DependencyProperty, System.Object)
   at EverythingToolbar.SearchWindow.AnimateShow(Double, Double, Double, Double, EverythingToolbar.Helpers.Edge)
   at EverythingToolbar.Behaviors.SearchWindowPlacement.OnShowing(System.Object, System.EventArgs)
   at NHotkey.HotkeyManagerBase.HandleHotkeyMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef, NHotkey.Hotkey ByRef)
   at NHotkey.Wpf.HotkeyManager.HandleMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
</details>

**Comment by srwi** [comment]
Hi @Roan-V, thank you for your detailed bug report. I was able to reproduce and fix the problem. The search window will now open near the deskband instead of on the monitor that contains the mouse cursor. The fix will be available in the next release.

**Comment by Roan-V** [comment]
Nice, thank you for the quick fix!
