### ISSUE TITLE
"More" filter - Can't select search flags (Match Case, Match Whole Word...) 

### ISSUE THREAD

**Issue by Mitia99** [srwi/EverythingToolbar#404]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.1.1

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 11 Pro 22H2 22621.1848

### Steps to reproduce

1. Open EverythinToolbar
2. Select any "More" filter (Audio/Compressed/Document....)
3. Select a search flag: Match case, Match Whole Word... 

### Expected Behavior

Select a search flag

### Actual Behavior

Can't select any search flag

### Screenshots

![Screenshot 2023-06-23 141430](https://github.com/srwi/EverythingToolbar/assets/56766778/35af79ab-d184-413f-a815-0c2eaba84b7a)
![Screenshot 2023-06-23 141828](https://github.com/srwi/EverythingToolbar/assets/56766778/b95a9f87-af8b-4c45-bb8c-0c573d33746e)

### Log output

2023-06-23 09:59:55.0332|INFO|Launcher|EverythingToolbar Launcher 1.1.1.0 started. OS: Microsoft Windows NT 10.0.22621.0|
2023-06-23 10:29:12.3093|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2023-06-23 10:29:12.8251|ERROR|EverythingToolbar.Behaviors.ThemeAwareness|Failed to get latest release version.|System.Net.Http.HttpRequestException: Une erreur s'est produite lors de l'envoi de la demande. ---> System.Net.WebException: Le nom distant n'a pas pu être résolu: 'api.github.com'
   à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   à System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Fin de la trace de la pile d'exception interne ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à EverythingToolbar.Controls.UpdateBanner.<GetLatestStableReleaseVersion>d__5.MoveNext() dans C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\UpdateBanner.xaml.cs:ligne 40
2023-06-23 14:06:39.0400|INFO|Launcher|EverythingToolbar Launcher 1.1.1.0 started. OS: Microsoft Windows NT 10.0.22621.0|
2023-06-23 14:06:39.7899|ERROR|EverythingToolbar.EverythingSearch|IPC is not available.|
2023-06-23 14:06:39.7899|ERROR|EverythingToolbar.EverythingSearch|Failed to get Everything version number. Is Everything running?|
2023-06-23 14:06:40.0053|ERROR|EverythingToolbar.Behaviors.ThemeAwareness|Failed to get latest release version.|System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'api.github.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EverythingToolbar.Controls.UpdateBanner.<GetLatestStableReleaseVersion>d__5.MoveNext() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Controls\UpdateBanner.xaml.cs:line 40

**Comment by Horst12** [comment]
These functions are available as buttons in the Toolbar GUI on the top right.


![Screenshot - 23 06 2023 , 13_57_50](https://github.com/srwi/EverythingToolbar/assets/38587340/e44f03f7-224f-4ba0-b82e-9f39ec42b421)

**Comment by Mitia99** [comment]
I see.

My issue is that I created custom filter so that I can't disable that setting.

I'd like to use search flags without using quick toggles though.

**Comment by srwi** [comment]
I think I could just allow changes to the search flags even for custom filters as long as they get set correctly when selecting another filter.

**Comment by srwi** [comment]
After looking at this problem again, I realized that I completely misunderstood filter flags. The behavior is fixed now and should be much more in line with how filters are handled in Everything. Thank you.
