### ISSUE TITLE
Error when trying to add Everything Toolbar to taskbar (System.Management.ManagementException: Invalid class)

### ISSUE THREAD

**Issue by fwrnke** [srwi/EverythingToolbar#442]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.2.0

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 10 version 21H2

### Steps to reproduce

1. Right-click on the Windows taskbar.
2. Go to the "Toolbars" option in the context menu that appears.
3. Select the "Everything Toolbar" from the list of available toolbars.
4. Error message is displayed.

### Expected Behavior

The "Everything Toolbar" is expected to initialize and added to the taskbar.

### Actual Behavior

Instead of being added to the Windows taskbar, an error message is shown labeled "Unhandled exception occured" (see screenshot).

### Screenshots

![2023-10-16_EverythingToolbar_error](https://github.com/srwi/EverythingToolbar/assets/78198155/d1277bbc-63fd-4a54-ac45-bcba83bdd145)

### Log output

```
2023-10-16 11:21:47.6394|INFO|CSDeskBand.CSDeskBandWpf|EverythingToolbar 1.2.0.0 started. OS: Microsoft Windows NT 10.0.19044.0|
2023-10-16 11:21:47.6459|ERROR|CSDeskBand.Deskband|Unhandled exception|System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'EverythingToolbar.Behaviors.ThemeAwareness' that matches the specified binding constraints threw an exception. ---> System.Management.ManagementException: Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at EverythingToolbar.Helpers.RegistryWatcher..ctor(RegistryEntry target) in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Helpers\RegistryWatcher.cs:line 45
   at EverythingToolbar.Behaviors.ThemeAwareness..ctor() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Behaviors\ThemeAwareness.cs:line 60
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at EverythingToolbar.ToolbarControl..ctor() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\ToolbarControl.xaml.cs:line 19
   at CSDeskBand.Deskband..ctor() in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar.Deskband\Deskband.cs:line 24
```

### Additional Information

Before opening this issue, I checked the "Windows Management Instrumentation" and "Windows Management Service" services (as described in #384). This didn't solve my issue, which was expected because my error message differs from the one in the linked issue.

I would appreciate any hints or a solution as I'm looking forward to use the toolbar.
Thanks for the great work in any case!

**Comment by srwi** [comment]
Hi @fwrnke, thank you for opening the issue. I think this might happen if your registry key `HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\SystemUsesLightTheme` doesn't exist. Could you please check that for me?

To my understanding it should normally exist starting with Win10 19H1.

If it does not exist for you, could you please create the DWORD key with value 1 or 0 and try enabling EverythingToolbar again to see if that fixes the problem?

**Comment by fwrnke** [comment]
Hi srwi,
thanks for your reply. I checked the registry key and it was already set (attached screenshot).
Is there another fix I could try?

![image](https://github.com/srwi/EverythingToolbar/assets/78198155/6e427fe1-e422-4457-ad68-aba897abe402)

**Comment by srwi** [comment]
Thank you for checking! I might have been on the wrong track there. I think you might be correct with your assumption that it has something to do with the WMI.

Since I also don't really know where to go from here I asked ChatGPT for guidance and maybe you could give the first suggestion a shot? We tried the other two already.

> 1. Run the winmgmt /verifyrepository command in Command Prompt to check the consistency of the WMI repository. If the repository is inconsistent, they can use the winmgmt /salvagerepository command to attempt to repair it.
> 2. Ensure that the Windows Management Instrumentation service is running on their system.
> 3. Check if the registry path HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize and the value name SystemUsesLightTheme exist in the Windows Registry Editor.

**Comment by fwrnke** [comment]
I could have thought about asking ChatGPT as well - good call ;)

Unfortunately, none of the options solved the issue. According to `winmgmt  /verifyrepository` the WMI repository is consistent and WMI is also running (and set to automatic startup).
I will try to investigate further and see if I can somehow fix this!
