### ISSUE TITLE
The setup assistant runs every time I restart the computer, and Win+S hotkey gets deleted

### ISSUE THREAD

**Issue by hollowstrawberry** [srwi/EverythingToolbar#521]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.3.4.0

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 11 23H2

### Steps to reproduce

Restart the computer and log in.

### Expected Behavior

EverythingToolbar launches and works as expected.

### Actual Behavior

Two things happen:  
1. The setup assistant comes up even though the program is already set up.
2. I get an error message saying the hotkey is used by something else, and consequently gets deleted. My hotkey is Win+S, which correctly replaces Windows' shortcut except after a restart.

### Screenshots

![image](https://github.com/user-attachments/assets/f0bd58d3-9a95-454d-af8c-509695c33804)

### Log output

2024-07-21 18:32:42.7404|INFO|Launcher|EverythingToolbar Launcher 1.3.4.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-07-21 18:32:43.1663|ERROR|EverythingToolbar.Helpers.ShortcutManager|Failed to register hotkey.|NHotkey.HotkeyAlreadyRegisteredException: Hot key is already registered. (Exception from HRESULT: 0x80070581) ---> System.Runtime.InteropServices.COMException: Hot key is already registered. (Exception from HRESULT: 0x80070581)
   --- End of inner exception stack trace ---
   at NHotkey.Hotkey.Register(IntPtr hwnd, String name)
   at NHotkey.HotkeyManagerBase.AddOrReplace(String name, UInt32 virtualKey, HotkeyFlags flags, EventHandler`1 handler)
   at EverythingToolbar.Helpers.ShortcutManager.AddOrReplace(String name, Key key, ModifierKeys modifiers, EventHandler`1 handler) in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Helpers\ShortcutManager.cs:line 69
2024-07-21 18:33:45.1299|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|
2024-07-21 18:35:05.8086|INFO|Launcher|EverythingToolbar Launcher 1.3.4.0 started. OS: Microsoft Windows NT 10.0.22631.0|
2024-07-21 18:35:06.1768|ERROR|EverythingToolbar.Helpers.ShortcutManager|Failed to register hotkey.|NHotkey.HotkeyAlreadyRegisteredException: Hot key is already registered. (Exception from HRESULT: 0x80070581) ---> System.Runtime.InteropServices.COMException: Hot key is already registered. (Exception from HRESULT: 0x80070581)
   --- End of inner exception stack trace ---
   at NHotkey.Hotkey.Register(IntPtr hwnd, String name)
   at NHotkey.HotkeyManagerBase.AddOrReplace(String name, UInt32 virtualKey, HotkeyFlags flags, EventHandler`1 handler)
   at EverythingToolbar.Helpers.ShortcutManager.AddOrReplace(String name, Key key, ModifierKeys modifiers, EventHandler`1 handler) in C:\Users\Stephan\Entwicklung\EverythingToolbar\EverythingToolbar\Helpers\ShortcutManager.cs:line 69
2024-07-21 18:35:14.6772|INFO|EverythingToolbar.EverythingSearch|Everything version: 1.4.1|

**Comment by srwi** [comment]
Hi @hollowstrawberry, sorry for the late reply.

1. Currently EverythingToolbar checks the presence of a shortcut in `%APPDATA%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar` that points to the `EverythingToolbar.Launcher.exe`. If it doesn't exist, it assumes not being set up yet and opens the setup assistant. Could you please check if a shortcut exists in your case? If that is not the case (Windows can be weird about this) you could try removing the pinned taskbar icon, rebooting your machine and working through the setup assistant again to pin the icon to the taskbar once again. Hopefully that resolves the problem.
2. This is a known issue: #249

**Comment by hollowstrawberry** [comment]
Thank you, that fixed 1!
