### ISSUE TITLE
EverythingToolbar will not launch

### ISSUE THREAD

**Issue by EugeneT3** [srwi/EverythingToolbar#523]
### Preflight Checklist

- [X] I have fully read the [README](https://github.com/srwi/EverythingToolbar/blob/master/README.md) and it did not solve the problem.
- [X] I have searched all [open and closed issues](https://github.com/srwi/EverythingToolbar/issues?q=) for the same bug report without success.

### EverythingToolbar Version

1.0.4

### Everything Version

1.4.1.1024 (x64)

### Windows Version

Windows 11 Pro 23H2

### Steps to reproduce

Launch EverythingToolbar.

### Expected Behavior

It is supposed to launch.

### Actual Behavior

Launches and then crashes.

### Log output

2024-07-30 23:19:13.6545|INFO|Launcher|EverythingToolbar Launcher 1.3.4.0 started. OS: Microsoft Windows NT 10.0.22631.0|

### Additional Information

Everything was working until tonight when I was trying to change a setting in the application ExplorerPatcher. It broke my Microsoft Explorer. I fixed my Explorer by uninstalling and reinstalling ExplorerPatcher. But I could not get Everythingtoolbar to launch let alone add it to the taskbar.

**Comment by srwi** [comment]
Hi @EugeneT3, are you using the launcher variant of EverythingToolbar or the deskband? Based on the log output it looks like you are using the launcher which I don't think should be affected by any ExplorerPatcher actions.

If you are using the deskband variant, reinstalling might fix the problem be reregistering the toolbar assembly in Windows.

**Comment by Hisayoo** [comment]
> Hi @EugeneT3, are you using the launcher variant of EverythingToolbar or the deskband? Based on the log output it looks like you are using the launcher which I don't think should be affected by any ExplorerPatcher actions.
> 
> If you are using the deskband variant, reinstalling might fix the problem be reregistering the toolbar assembly in Windows.

I am getting the same issue on a fresh installation. I am trying to install this for the first time but after launching it, it instantly crashes and is only visible in the Task manager for 1-3 seconds. This is the AppCrash file in ReportArchive

```Version=1
EventType=CLR20r3
EventTime=133672758831293797
ReportType=2
Consent=1
UploadTime=133672758836103633
ReportStatus=268435456
ReportIdentifier=478e8c6c-fca8-474d-91ee-ffab756f9b2b
IntegratorReportIdentifier=df6381e9-376b-4aa8-b5d6-541db36f1561
Wow64Host=34404
NsAppName=EverythingToolbar.Launcher.exe
OriginalFilename=EverythingToolbar.Launcher.exe
AppSessionGuid=00002938-0001-020b-b2ae-fa79aae6da01
TargetAppId=W:0006d136be981d5d49d5933c3450b514051300000000!0000e2a45047dc20b1be40bff67376393a4f20fdf974!EverythingToolbar.Launcher.exe
TargetAppVer=2076//05//05:08:31:36!0!EverythingToolbar.Launcher.exe
BootId=4294967295
TargetAsId=648
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=4c0f1b3e53e5db6a0af0f2a7b988e879
Response.BucketTable=5
Response.LegacyBucketId=1941318241582901369
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=EverythingToolbar.Launcher.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=1.3.4.0
Sig[2].Name=Problem Signature 03
Sig[2].Value=c806dd68
Sig[3].Name=Problem Signature 04
Sig[3].Value=EverythingToolbar.Launcher
Sig[4].Name=Problem Signature 05
Sig[4].Value=1.3.4.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=c806dd68
Sig[6].Name=Problem Signature 07
Sig[6].Value=17
Sig[7].Name=Problem Signature 08
Sig[7].Value=ba
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.UnauthorizedAccess
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.22631.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=76c1
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=76c12eefbb762f4b4f667aba1fba4c11
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=bafc
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=bafc6ee031baf89c89d7e6a93c293e21
UI[2]=C:\Program Files (x86)\EverythingToolbar\EverythingToolbar.Launcher.exe
LoadedModule[0]=C:\Program Files (x86)\EverythingToolbar\EverythingToolbar.Launcher.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\sechost.dll
LoadedModule[8]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[9]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[10]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[11]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[12]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[13]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[14]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[15]=C:\WINDOWS\System32\USER32.dll
LoadedModule[16]=C:\WINDOWS\System32\win32u.dll
LoadedModule[17]=C:\WINDOWS\SYSTEM32\VCRUNTIME140_1_CLR0400.dll
LoadedModule[18]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[19]=C:\WINDOWS\SYSTEM32\VCRUNTIME140_CLR0400.dll
LoadedModule[20]=C:\WINDOWS\SYSTEM32\ucrtbase_clr0400.dll
LoadedModule[21]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[22]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[23]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[24]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[25]=C:\WINDOWS\System32\psapi.dll
LoadedModule[26]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\3d9bc59f7d2daa55a95ce77da3459365\mscorlib.ni.dll
LoadedModule[27]=C:\WINDOWS\System32\ole32.dll
LoadedModule[28]=C:\WINDOWS\System32\combase.dll
LoadedModule[29]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[30]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[31]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[32]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System\6bb642686313ded6b7fbaa03f3491173\System.ni.dll
LoadedModule[33]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Core\973d111169c60f5eb353090e4bcaeaa9\System.Core.ni.dll
LoadedModule[34]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\WindowsBase\99516a10b8839e5c39795f333e0ce71a\WindowsBase.ni.dll
LoadedModule[35]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[36]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[37]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[38]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PresentationCore\ca605636d2b02bc98369608b364e8b8c\PresentationCore.ni.dll
LoadedModule[39]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\c1902dcc0a1c04011c52b1401d392781\PresentationFramework.ni.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\dwrite.dll
LoadedModule[41]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[42]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\MSVCP140_CLR0400.dll
LoadedModule[44]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[45]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Drawing\bdca308c5efa287a24ccc9e50f3d5693\System.Drawing.ni.dll
LoadedModule[46]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\d5d34fa31875936a5eaa7275e1c232f8\System.Windows.Forms.ni.dll
LoadedModule[47]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xaml\e2f887ccee2c451c3e1535b0a88dc98a\System.Xaml.ni.dll
LoadedModule[48]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Configuration\390f06a636329311fbf82b2a9ef94360\System.Configuration.ni.dll
LoadedModule[49]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xml\f717224ad0dd85f6d3e71ab8b7243d70\System.Xml.ni.dll
LoadedModule[50]=C:\WINDOWS\System32\shell32.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[53]=C:\WINDOWS\System32\SHCORE.dll
LoadedModule[54]=C:\WINDOWS\SYSTEM32\profapi.dll
LoadedModule[55]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[56]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\netutils.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\srvcli.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\virtdisk.dll
LoadedModule[62]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22621.3672_none_2713b9d173822955\comctl32.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[64]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[65]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[66]=C:\Windows\System32\Windows.ApplicationModel.dll
LoadedModule[67]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Management\05c12eb2c16c72f30f178f4cf3b4a88f\System.Management.ni.dll
LoadedModule[68]=C:\WINDOWS\system32\wbem\wmiutils.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\wbemcomn.dll
LoadedModule[70]=C:\WINDOWS\system32\wbem\wbemprox.dll
LoadedModule[71]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll
LoadedModule[72]=C:\WINDOWS\system32\wbem\wbemsvc.dll
LoadedModule[73]=C:\WINDOWS\system32\wbem\fastprox.dll
LoadedModule[74]=C:\WINDOWS\SYSTEM32\amsi.dll
LoadedModule[75]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[76]=C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.24070.5-0\MpOav.dll
LoadedModule[77]=C:\Windows\System32\Windows.UI.dll
LoadedModule[78]=C:\Windows\System32\Windows.UI.Immersive.dll
LoadedModule[79]=C:\Windows\System32\twinapi.appcore.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\DWMAPI.dll
LoadedModule[81]=C:\WINDOWS\SYSTEM32\d3d9.dll
LoadedModule[82]=C:\WINDOWS\SYSTEM32\dxcore.dll
LoadedModule[83]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_866484083fc526af\nvldumdx.dll
LoadedModule[84]=C:\WINDOWS\SYSTEM32\msasn1.dll
LoadedModule[85]=C:\WINDOWS\SYSTEM32\cryptnet.dll
LoadedModule[86]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[87]=C:\WINDOWS\SYSTEM32\drvstore.dll
LoadedModule[88]=C:\WINDOWS\SYSTEM32\devobj.dll
LoadedModule[89]=C:\WINDOWS\SYSTEM32\cfgmgr32.dll
LoadedModule[90]=C:\WINDOWS\SYSTEM32\wldp.dll
LoadedModule[91]=C:\WINDOWS\System32\wintrust.dll
LoadedModule[92]=C:\WINDOWS\System32\imagehlp.dll
LoadedModule[93]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_866484083fc526af\nvgpucomp64.dll
LoadedModule[94]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_866484083fc526af\nvd3dumx.dll
LoadedModule[95]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[96]=C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
LoadedModule[97]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Presentatioaec034ca#\526af49cbadf667e7fcb9b412fd839c3\PresentationFramework.Aero2.ni.dll
LoadedModule[98]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Microsoft.CSharp\7113c6cd2cf54a829d898f604995490f\Microsoft.CSharp.ni.dll
LoadedModule[99]=C:\WINDOWS\SYSTEM32\sxs.dll
LoadedModule[100]=C:\WINDOWS\SYSTEM32\LINKINFO.dll
LoadedModule[101]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Dynamic\9273abde3a61591af8f5c81d50a3b843\System.Dynamic.ni.dll
LoadedModule[102]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=22631
OsInfo[3].Key=ubr
OsInfo[3].Value=3880
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1041
OsInfo[7].Key=geoid
OsInfo[7].Value=94
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222785062
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.22621.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32532
OsInfo[19].Key=svolsz
OsInfo[19].Value=1862
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=220506
OsInfo[22].Key=bldtm
OsInfo[22].Value=1250
OsInfo[23].Key=bldbrch
OsInfo[23].Value=ni_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.22621.3880.amd64fre.ni_release.220506-1250
OsInfo[30].Key=buildflightid
OsInfo[30].Value=ace658e6-9595-4c7e-8226-67f5a351f23d
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=MD:283BAEF,ME:2E3922F,ME:2E30985,MD:2E30A2A
OsInfo[34].Key=fconid
OsInfo[34].Value=19638787,0,2,0;23531064,2,2,0;23562335,2,2,0;23563673,2,2,0;26742989,0,1,0;32862274,0,2,0;35681102,0,1,0;36803287,0,2,1;36803295,0,2,0;36803303,0,2,1;38277973,0,1,0;38859191,0,2,1;39145991,0,2,0;39263329,1,2,0;39281392,0,2,0;40025975,0,1,0;40616880,0,1,1;40883769,0,1,0;40981503,0,1,0;41135193,0,1,1;41137130,0,1,0;41267076,0,2,1;41342175,0,1,1;41655236,0,2,0;41772259,0,2,1;42052423,0,2,0;42105254,0,2,0;43133808,1,2,1;43169616,0,1,1;43203978,0,2,1;43572857,0,2,1;43772553,0,1,0;43844371,0,1,1;43978769,0,1,1;44325080,0,1,0;44521793,0,1,0;44552141,0,1,0;44776738,0,2,0;45009259,0,1,1;45185354,0,2,0;45286373,0,1,1;45732051,0,2,0;45796396,0,2,0;45991456,0,1,1;46457961,0,1,1;46541070,0,2,0;46551074,0,1,1;46557400,0,1,1;47115450,0,1,1;47134595,0,1,1;47205155,0,2,1;47557358,0,2,1;47681899,0,1,1;47916854,0,1,0;47973375,0,1,0;48057519,0,2,1;48296377,0,1,0;48433541,0,2,0;48433706,0,1,0;48433719,0,1,0;48468527,0,2,0;48468541,0,2,0;48503047,0,2,0;49175271,0,2,0;49204591,0,1,1;49239926,0,1,1;49309588,0,1,0;49408394,0,1,0;49577493,0,1,0;49615603,0,1,1;49689210,0,1,0;49822061,0,1,1;50174338,0,1,0;50556886,0,1,0;50557073,0,1,0;50564196,0,1,0;50564332,0,1,0;50565209,0,1,0;50565295,0,1,0;50762615,0,1,1
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
OsInfo[38].Key=servicinginprogress
OsInfo[38].Value=0
OsInfo[39].Key=featureupdatependingreboot
OsInfo[39].Value=0
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=EverythingToolbar
AppPath=C:\Program Files (x86)\EverythingToolbar\EverythingToolbar.Launcher.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=8DBF3E607F626D68A3FF829AAD7C3F7C
MetadataHash=-69025758

**Comment by EugeneT3** [comment]
Quick update* I upgraded my Windows to 24H or whatever the coming version of Windows will be in hopes it would fix some other issues I've been having with Microsoft Explorer and hopefully get the toolbar working again and still nothing.

**Comment by GMss2** [comment]
I am having same issue. And I have reinstalled, but nothing worked.

**Comment by srwi** [comment]
Unfortunately it is very hard to find the cause of it without a descriptive error message (not your fault at all). Would anybody of you be willing to help me out by trying out some older versions of EverythingToolbar to see which version started causing this problem? This would help me out tremendously.

**Comment by GMss2** [comment]
> Unfortunately it is very hard to find the cause of it without a descriptive error message (not your fault at all). Would anybody of you be willing to help me out by trying out some older versions of EverythingToolbar to see which version started causing this problem? This would help me out tremendously.

I uninstalled everythingtoolbar-1.3.4 and installed the version 1.3.3. And it is working normally now.

**Comment by Hisayoo** [comment]
> > Unfortunately it is very hard to find the cause of it without a descriptive error message (not your fault at all). Would anybody of you be willing to help me out by trying out some older versions of EverythingToolbar to see which version started causing this problem? This would help me out tremendously.
> 
> I uninstalled everythingtoolbar-1.3.4 and installed the version 1.3.3. And it is working normally now.

Same for me. 1.3.3 works!

**Comment by GMss2** [comment]
> Unfortunately it is very hard to find the cause of it without a descriptive error message (not your fault at all). Would anybody of you be willing to help me out by trying out some older versions of EverythingToolbar to see which version started causing this problem? This would help me out tremendously.

And deskband can work both version.

**Comment by srwi** [comment]
Thanks a lot for the speedy feedback! I can work with that knowledge. I'll try to look into it hopefully this week.

**Comment by EugeneT3** [comment]
Not to beat a dead horse but I can confirm using 1.33 does work for me as well. Thank you, guys!

**Comment by sf000000** [comment]
Getting same behavior as OP on 1.3.2, 1.3.3 and 1.3.4 

2024-09-03 12:29:16.1542|INFO|Launcher|EverythingToolbar Launcher 1.3.4.0 started. OS: Microsoft Windows NT 10.0.26100.0|

```
Log Name:      Application
Source:        .NET Runtime
Date:          9/3/2024 12:29:16 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      win
Description:
Application: EverythingToolbar.Launcher.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.FileSystemWatcher.set_Path(System.String)
   at EverythingToolbar.Launcher.SetupAssistant.CreateFileWatcher()
   at EverythingToolbar.Launcher.SetupAssistant..ctor(System.Windows.Forms.NotifyIcon)
   at EverythingToolbar.Launcher.Launcher+LauncherWindow..ctor(System.Windows.Forms.NotifyIcon)
   at EverythingToolbar.Launcher.Launcher.Main()
```

**Comment by Hex34568** [comment]
> I am having same issue. And I have reinstalled, but nothing worked.

did u manage to find a fix? i switched from windows 10 to and 11 and it just crashes on launch now

**Comment by Hex34568** [comment]
> > > Unfortunately it is very hard to find the cause of it without a descriptive error message (not your fault at all). Would anybody of you be willing to help me out by trying out some older versions of EverythingToolbar to see which version started causing this problem? This would help me out tremendously.
> > 
> > 
> > I uninstalled everythingtoolbar-1.3.4 and installed the version 1.3.3. And it is working normally now.
> 
> Same for me. 1.3.3 works!

it doesn't for me unfortunately :(

**Comment by srwi** [comment]
Does this version work for you? https://github.com/srwi/EverythingToolbar/actions/runs/10743582890/artifacts/1902589694

If not, could you please post the log output located at `%TEMP%\EverythingToolbar.log`?

**Comment by Hex34568** [comment]
> %TEMP%\EverythingToolbar.log

same issue did not work
[EverythingToolbar.log](https://github.com/user-attachments/files/16912068/EverythingToolbar.log)

**Comment by srwi** [comment]
Version 1.4.0 _should_ fix both crashes mentioned here. Please let me know if that is finally the case for you. Again, if it still crashes, please post the log outputs again. Thank you!

**Comment by Hex34568** [comment]
> Version 1.4.0 _should_ fix both crashes mentioned here. Please let me know if that is finally the case for you. Again, if it still crashes, please post the log outputs again. Thank you!

It worked! thank you for uh fixing it
